version: '3.8' # docker compose 的版本

services: # 容器
  servicename: # 服务名字，这个名字也是内部 bridge网络可以使用的 DNS name
    container_name: # container 的名字 ，但使用自定義名字會影響到 scale !!
    build: # 對應 compose build 的功能 
      context: # 指定需要 build 的文件夾
      dockerfile: # 指定 文件夾內的 dockerfile name
    image: # image 的名字
    restart: always
    command: # 可选，如果设置，则会覆盖默认镜像里的 CMD命令
    environment: # 可选，相当于 docker run里的 --env
    volumes: # 可选，相当于docker run里的 -v
    networks: # 可选，相当于 docker run里的 --network
    ports: # 可选，相当于 docker run里的 -p
  servicename2:

volumes: # 可选，相当于 docker volume create

networks: # 可选，相当于 docker network create
