version: "3.8"

services: # 容器
  pg: # 服务名字，这个名字也是内部 bridge网络可以使用的 DNS name
    image: postgres:alpine3.17
    restart: always
    environment: # 可选，相当于 docker run里的 --env
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    volumes: # 可选，相当于docker run里的 -v
      - //e/homePG/seal/data:/var/lib/postgresql/data
    ports: # 可选，相当于 docker run里的 -p
      - 5433:5432
    networks:
      - net-demo
  
  express-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-demo
    ports:
      - 3000:3000
    networks:
      - net-demo

networks:
  net-demo:
    name: net-demo